parameters:
  #test
   randaug_N: [ 0]
   randaug_M: [ 0]
   #learning_rate: [0.001, 0.01,0.05,0.1]
   #weight_decay: [0.0001,]
#  mem_ratio: [1,]
   mem_iters: [1,2,5,10,20]

  #real
#  learning_rate: [0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03, 0.1]
#  weight_decay: [0.0001, 0.001, 0.01, 0.1]
  
