parameters:
  #experiment
  num_runs: 1 #5
  seed: 1259053
  # optimizer
  optimizer: SGD
  epoch: 1
  batch: 10
  test_batch: 128
  # validation
  val_size: 0.0
  num_val: 2 #17
  num_runs_val: 1 #3
  # data general
  fix_order: False
  plot_sample: False
  online: True

  exp_name: para17_7_4

  dataset_random_type: "task_random"
  switch_buffer_type: "one_buffer"
  RL_type: "NoRL"
  use_test_buffer: False
  test_mem_type: "after"
  use_tmp_buffer: False
  frozen_old_fc: False
  mem_iters: 1
  incoming_ratio: 1
  mem_ratio: 1
  save_prefix: "joint_training"
  replay_old_only: False
  only_task_seen: False
  use_softmaxloss: False
  buffer_tracker: False
  error_analysis: False
  start_mem_iters: -1
  close_loop_mem_type: "random"
  joint_replay_type: "together"
  online_hyper_tune: False

  lambda_: 100
  nmc_trick : False
  learning_rate: 0.1
  weight_decay: 0.0001

  randaug: True
  #randaug_M: 14
  resnet_size: "reduced"
  aug_target: "both"
  aug_start: 0
  randaug_type: "static"
  scraug: False
  immediate_evaluate: False
  test_add_buffer: False
  dyna_mem_iter: "STOP_loss"
  stop_ratio : 3
  offline: False


